microsoft/edx-platform

lms/envs/aws.py
Fix to make Azure storage config optional
@eltoncarr @sdolenc
=> DB bootstrap fixes

common/djangoapps/track/management/commands/ship_tracking_logs.py
=> Fix blob does not exist error on uploading logs

common/djangoapps/enrollment/data.py
Restricting Cross site course enrollment based on SITE course_org_filter.
=> Restricting Cross site course enrollment based on SITE organization

common/static/common/js/discussion/views/discussion_content_view.js
Tested with IE11, Edge, FF, Chrome
=> Fix forum voting button toggle for IE

openedx/core/djangoapps/site_configuration/middleware.py
Changes middleware to not hold onto request state in class. This was causing both sites to be restricted in a stamp instance.
openedx/core/djangoapps/site_configuration/middleware.py
[//]: # ( …
=> Fixed LoginRequiredMiddleware 

lms/static/js/my_courses_dropdown.js
-      It will close drop down automatically when you will click on screen anywhere other than drop-down.
-      SignIn Production site and open drop-down. Try to close it by clicking outside of drop-down.
-     Before : drop-down doesn't automatically close when click outside on screen.
After: drop-down does automatically close when click outside on screen.
-       Bug:  84810
1. Resolve …
=> UX: Header user/profile drop-down doesn't automatically close

common/djangoapps/student/views.py, common/djangoapps/util/views.py, lms/djangoapps/branding/__init__.py, lms/djangoapps/branding/views.py, lms/djangoapps/shoppingcart/api.py, lms/lib/courseware_search/lms_filter_generator.py, lms/lib/courseware_search/test/test_lms_filter_generator.py, openedx/core/djangoapps/content/course_overviews/models.py, openedx/core/djangoapps/content/course_overviews/tests.py, openedx/core/djangoapps/site_configuration/helpers.py, openedx/core/djangoapps/site_configuration/models.py, openedx/core/djangoapps/site_configuration/tests/test_helpers.py
WL-926
This is a cherry pick of the PR https://github.com/edx/edx-platform/pull/14471  This provides the support for multiple orgs in platform
After adding this PR he should add multiple orgs in site_configurations in admin panel and verify it for multiple sites.
By creating a course with specific org, lets say "Shared" and adding that org in course_org_filter in siteconfigurations will show that course in all sites that have this org in course_org_filter.
Task 99204
1. If merging from development …
=> Add support for multi-org sites

cms/static/js/base.js, cms/static/sass/views/_dashboard.scss, cms/templates/course_outline.html, cms/templates/index.html, openedx/core/djangoapps/site_configuration/helpers.py
-  It creates dropdown for each course. Dropdown will have all site's display name for which course is 
targeted to. 
- Open CMS. View Live will redirect to course organization.
-Before : View Live redirects based on organization of course.
-After   : View Live button will redirect based on selected value of dropdown. 
Feature : 99205
1. (reverse merge) If …
=> View-Live-DropDown

common/djangoapps/student/tests/test_create_account.py, common/djangoapps/student/tests/test_password_policy.py, common/djangoapps/student/views.py, common/djangoapps/third_party_auth/tests/specs/base.py, openedx/core/djangoapps/external_auth/tests/test_ssl.py
This will add 'created_on_site' UserAttribute on account creation and adds Domain name of the site.
This was a cherry pick of **PR 14544** from edx/edx-platform. I have resolved the conflicts and removed extra code.
After enabling multiple sites, creating a account on any site will add a 'created_on_site' on mysql "**student_userattribute**" table 
Register on any of the two sites and you can see a row inserted in student_userattribute table in mysql that has the info of user's related to sites.
99346
1. If you're merging into the development branch then "flatten" or "squash" …
=> Set 'created_on_site' UserAttribute on account creation

common/djangoapps/student/views.py, lms/templates/registration/password_reset_done.html
Changing the forget pwd change text
Click on the forget password button and enter the email . Now you can see the text changes and show the email address to where the password reset email has been sent
The text was not clear and there was no indication of email to where the password resent email has been sent
88245
1. (reverse merge) If you merged into master …
=> Forget pwd changes

cms/templates/index.html
- allows only staff users to create library.
- Try to create library without staff permission
Before : Non staff users can create library.
After : Only staff user can create library.
User Story 84807
1. (reverse merge) If you merged into master then check to see if there are any changes in master that can be merged down to the development branch (like …
=> craete-library-access

common/djangoapps/student/tests/test_reset_password.py
Fixing tests
[//]: # ( todo: If you merged into development branch then verify change in our "rolling deployment" environment. Then notify stakeholders interested in or involved with the …
=> Fixing tests

cms/envs/docker_devstack.py, lms/envs/docker_devstack.py
Adds environment settings for logging in docker devstack
lms/envs/devstack_docker.py
[//]: # ( todo: If you merged into development branch then verify change in our "rolling deployment" …
=> Adding env settings for running edx-platform in docker

cms/static/sass/studio-main-v1-rtl.scss, cms/static/sass/studio-main-v1.scss, common/lib/xmodule/xmodule/static_content.py, lms/static/sass/_build-base-v1-rtl.scss, lms/static/sass/_build-base-v1.scss, lms/static/sass/lms-course-rtl.scss, lms/static/sass/lms-course.scss, lms/static/sass/lms-footer-edx-rtl.scss, lms/static/sass/lms-footer-edx.scss, lms/static/sass/lms-footer-rtl.scss, lms/static/sass/lms-footer.scss
Removes unnecessary changes
[//]: # ( todo: If you merged into development branch then verify change in our "rolling deployment" environment. Then notify stakeholders interested in or involved …
=> Apply fixes to pull out unnecessary changes

lms/static/coffee/src/customwmd.coffee
- Remind Learners not to post PII data in the discussion forums.
- lms --> click on any course --> discussion --> add Post --> no reminder for learner.
- Before : No Reminder for Learners about posting PII data in discussion forum.
After :  Remind Learners not post PII data in discussion forum
USER STORY : 99294
1. (reverse merge) If you merged into master …
=> discussion-forum-reminder

lms/djangoapps/courseware/tests/test_course_info.py, lms/templates/courseware/info.html
- swap course title and course number to improve UI.
- course about page display organization's followed by course number.
- swapping course title and course number for UI impovement.
- 99583
1. (reverse merge) If you merged from the development branch into master then check to see if there are any changes in master that can be merged down to the development branch (like hotfixes, etc). In …
=> course-title-UI

common/lib/xmodule/xmodule/css/capa/display.scss
The label text for problems types does word wrap
Create the Unit with the lengthy problem(Eg: Multiple Choice Questions, Drope down Qns) in the cms.
Before: The text for problems does not word wrap
After: The text for problems does the word wrap
Bug:91392
1. (reverse merge) If you merged from the development branch into master then check to see if there are any changes in master that can be …
=> ElakkiyaText Wrap

cms/static/js/base.js, cms/static/sass/views/_dashboard.scss, cms/templates/course_outline.html, cms/templates/index.html, openedx/core/djangoapps/site_configuration/helpers.py
holding back multi-org courses in edx-platform (originally PR 38)
=> Revert "View-Live-DropDown"

common/djangoapps/student/views.py, common/djangoapps/util/views.py, lms/djangoapps/branding/__init__.py, lms/djangoapps/branding/views.py, lms/djangoapps/shoppingcart/api.py, lms/lib/courseware_search/lms_filter_generator.py, lms/lib/courseware_search/test/test_lms_filter_generator.py, openedx/core/djangoapps/content/course_overviews/models.py, openedx/core/djangoapps/content/course_overviews/tests.py, openedx/core/djangoapps/site_configuration/helpers.py, openedx/core/djangoapps/site_configuration/models.py, openedx/core/djangoapps/site_configuration/tests/test_helpers.py
holding back multi-org courses in edx-platform (originally PR 36)
=> Revert "Add support for multi-org sites"

cms/static/js/base.js, cms/static/sass/views/_dashboard.scss, cms/templates/course_outline.html, cms/templates/index.html, common/djangoapps/student/tests/test_create_account.py, common/djangoapps/student/tests/test_password_policy.py, common/djangoapps/student/views.py, common/djangoapps/third_party_auth/tests/specs/base.py, common/djangoapps/util/views.py, lms/djangoapps/branding/__init__.py, lms/djangoapps/branding/views.py, lms/djangoapps/shoppingcart/api.py, lms/lib/courseware_search/lms_filter_generator.py, lms/lib/courseware_search/test/test_lms_filter_generator.py, openedx/core/djangoapps/content/course_overviews/models.py, openedx/core/djangoapps/content/course_overviews/tests.py, openedx/core/djangoapps/external_auth/tests/test_ssl.py, openedx/core/djangoapps/site_configuration/helpers.py, openedx/core/djangoapps/site_configuration/models.py, openedx/core/djangoapps/site_configuration/tests/test_helpers.py
holding back multi-org courses in edx-platform
=> Oxa/rc 2.3.0 revert

cms/djangoapps/contentstore/tests/test_libraries.py, cms/djangoapps/contentstore/views/course.py, cms/djangoapps/contentstore/views/library.py, cms/djangoapps/contentstore/views/tests/test_course_index.py, cms/djangoapps/contentstore/views/tests/test_library.py, cms/templates/index.html, openedx/core/djangoapps/site_configuration/helpers.py
- cms.env.json config for non-staff user
-  Try to create library without staff permission.
- cms.env.json has library access configuration
- 100075
[//]: # ( todo: If you merged into …
=> Library-btn-access-update

cms/static/js/base.js, cms/static/sass/views/_dashboard.scss, cms/templates/course_outline.html, cms/templates/index.html, common/djangoapps/student/tests/test_create_account.py, common/djangoapps/student/tests/test_password_policy.py, common/djangoapps/student/views.py, common/djangoapps/third_party_auth/tests/specs/base.py, common/djangoapps/util/views.py, lms/djangoapps/branding/__init__.py, lms/djangoapps/branding/views.py, lms/djangoapps/shoppingcart/api.py, lms/lib/courseware_search/lms_filter_generator.py, lms/lib/courseware_search/test/test_lms_filter_generator.py, openedx/core/djangoapps/content/course_overviews/models.py, openedx/core/djangoapps/content/course_overviews/tests.py, openedx/core/djangoapps/external_auth/tests/test_ssl.py, openedx/core/djangoapps/site_configuration/helpers.py, openedx/core/djangoapps/site_configuration/models.py, openedx/core/djangoapps/site_configuration/tests/test_helpers.py
This reverts commit 029a101f369d10b244818e7cbebd5ffde7bfaf6d.
=> Revert "Oxa/rc 2.3.0 revert (#62)"

cms/templates/course_outline.html
There were two lines that in a template that had a new line in the middle of a string.
Fixed these to both be one line.
cms/templates/course_outline.html
line 215
1. (reverse merge) If you merged from the development branch into master then check to see if there are any changes in master that can be merged down to the development branch (like hotfixes, etc). In this case, use github's UI for …
=> Fixes CMS render error with line ending.

lms/envs/aws.py
we've started seeing deployment failures due to a how we're removing entries from a dictionary. There are known cases where the key will not exist. We are switching to a "safe" remove strategy that won't throw an error when the key isn't found
n/a short review
simply attempting a deployment will trigger the failure. more directly: running the following script will reliably throw the exception: /edx/bin/edxapp-migrate-lms
100648
1. Delete the remote feature …
=> fixing runtime error during deploy

requirements/edx/base.txt
we are updating the django storage verion.
Right now we are unable to run the CMS migrations in our platform. after updating the django version we can run them without any errors.
Before: Error on running CMS migrations.
After: Migrations will run sucessfully.
100043
1. (reverse merge) If you merged from the development branch into master then check to see if there are any changes in master …
=> Updating the djanago storage version

common/djangoapps/student/forms.py, common/djangoapps/student/tests/test_reset_password.py, common/djangoapps/student/views.py, lms/djangoapps/student_account/views.py, openedx/core/djangoapps/user_api/accounts/api.py, openedx/core/djangoapps/user_api/accounts/tests/test_api.py
Cherry Picks and applies patch for host header poisoning of password reset emails
100447
1. (reverse merge) If you merged from the development branch into master then check to see if there are any changes in master that can be merged down to the development branch (like hotfixes, etc). In this case, use github's UI for feedback and the git command line interface for the actual merge.
[//]: # …
=> Apply security patch for poisoned headers on password reset emails.

lms/envs/common.py
To prevent the browser from guessing the content type and force it to always use the type provided in the Content-Type header, we need this to be enables as true
SECURE_CONTENT_TYPE_NOSNIFF will be added as true in settings file which is false by default.
97960
1. (reverse merge) If you merged from the development branch into master then check to see if there are any changes in master that …
=> Adding SECURE_CONTENT_TYPE_NOSNIFF variable.

lms/envs/aws.py
What does this PR do? Please provide some context
Avoid the duplicates from the Preferred Language drop down
Where should the reviewer start?
Register as a new user user in the home page
How can this be manually tested? (brief repro steps)
Before: The Preferred Language drop down has few duplicates values
After: No duplicates in the language list
What are the relevant TFS items? (list id numbers)
Bug 100756
1. Resolve …
=> Elakkiya LangBug fix

lms/djangoapps/student_account/views.py, lms/envs/aws.py
aligning settings name with edx-configuration
=> aligning settings name with edx-configuration

lms/djangoapps/student_account/test/test_views.py, lms/djangoapps/student_account/urls.py, lms/djangoapps/student_account/views.py, lms/envs/aws.py, lms/urls.py
Platform changes to call the common cookie URL
urls.py
I will send the link to the deployment with these changes - here are some checks;
Clean browser from cookies, upon launch of the site you should see the banner and only 2 essential cookies should be loaded
Upon click on a link/button - the banner should be removed and non-essential cookies are allowed in
101096
1. (reverse merge) If you …
=> Platform changes for common cookie URL call 

lms/djangoapps/student_account/test/test_views.py, lms/djangoapps/student_account/urls.py, lms/djangoapps/student_account/views.py, lms/envs/aws.py, lms/urls.py, scripts/docker-run-tests.sh
Revert cookie changes +fix the travis not getting latest changes
travis.yml file
Travis CI check should be good after this checkin
None
1. (reverse merge) If you merged from the development branch into master then check to see if there are any changes in master that can be merged down to the development branch (like hotfixes, etc). In this case, use github's UI for feedback and the git …
=> Revert cookie changes +fix the travis not getting latest changes

.eslintignore, .travis.yml, cms/static/js/base.js, common/djangoapps/student/tests/test_create_account.py, common/lib/xmodule/xmodule/js/spec/capa/display_spec.coffee, common/test/acceptance/pages/lms/discussion.py, common/test/acceptance/tests/lms/test_lms_dashboard.py, common/test/acceptance/tests/lms/test_lms_edxnotes.py, common/test/acceptance/tests/lms/test_lms_help.py, common/test/acceptance/tests/studio/test_import_export.py, common/test/acceptance/tests/studio/test_studio_help.py, common/test/acceptance/tests/studio/test_studio_outline.py, lms/djangoapps/student_account/test/test_views.py, lms/djangoapps/student_account/urls.py, lms/djangoapps/student_account/views.py, lms/envs/aws.py, openedx/core/djangoapps/site_configuration/helpers.py, openedx/core/djangoapps/site_configuration/middleware.py, openedx/core/djangoapps/site_configuration/tests/test_middleware.py, scripts/docker-run-tests.sh
Merge cookie changes to release branch
Please go to the equivalent PRs:
Actual cookie change: https://github.com/Microsoft/edx-platform/pull/99
Needed for several test fixes (e.g. refreshMath test + Markdown js): https://github.com/Microsoft/edx-platform/pull/91
Needed to get the latest changes from the cookie branch: https://github.com/Microsoft/edx-platform/pull/96
Please check respective commits for how to test
101096 …
=> Merge cookie changes to release branch

common/djangoapps/student/tests/test_certificates.py, common/djangoapps/student/views.py
- change certificate URL if course organization is in SHARED_ORG.
- SHARED_ORG  list could be [Shared , All ,etc..]
-  DashBoard --> View Certificate --> URL redirects to default site domain.
AFTER : For Employee site certificate URL will redirect based on course org .if it is in 
SHARED_ORG it will redirect to CERT_URL domain
Bug:102033
1. (reverse merge) If you merged from the development …
=> Dashboard Cerl_url

cms/templates/course_outline.html
=> release to dev

cms/static/js/base.js, cms/static/sass/views/_dashboard.scss, cms/templates/course_outline.html, cms/templates/index.html, common/djangoapps/student/tests/test_create_account.py, common/djangoapps/student/tests/test_password_policy.py, common/djangoapps/student/views.py, common/djangoapps/third_party_auth/tests/specs/base.py, common/djangoapps/util/views.py, common/lib/xmodule/xmodule/css/capa/display.scss, lms/djangoapps/branding/__init__.py, lms/djangoapps/branding/views.py, lms/djangoapps/shoppingcart/api.py, lms/lib/courseware_search/lms_filter_generator.py, lms/lib/courseware_search/test/test_lms_filter_generator.py, openedx/core/djangoapps/content/course_overviews/models.py, openedx/core/djangoapps/content/course_overviews/tests.py, openedx/core/djangoapps/external_auth/tests/test_ssl.py, openedx/core/djangoapps/site_configuration/helpers.py, openedx/core/djangoapps/site_configuration/models.py, openedx/core/djangoapps/site_configuration/tests/test_helpers.py
=> re-applying multiSiteCourse holdback

.travis.yml, cms/static/js/base.js, cms/static/sass/views/_dashboard.scss, cms/templates/course_outline.html, cms/templates/index.html, common/djangoapps/student/tests/test_certificates.py, common/djangoapps/student/tests/test_create_account.py, common/djangoapps/student/tests/test_password_policy.py, common/djangoapps/student/views.py, common/djangoapps/third_party_auth/tests/specs/base.py, common/djangoapps/util/views.py, lms/djangoapps/branding/__init__.py, lms/djangoapps/branding/views.py, lms/djangoapps/courseware/tests/test_views.py, lms/djangoapps/courseware/views/views.py, lms/djangoapps/shoppingcart/api.py, lms/lib/courseware_search/lms_filter_generator.py, lms/lib/courseware_search/test/test_lms_filter_generator.py, openedx/core/djangoapps/content/course_overviews/models.py, openedx/core/djangoapps/content/course_overviews/tests.py, openedx/core/djangoapps/external_auth/tests/test_ssl.py, openedx/core/djangoapps/site_configuration/helpers.py, openedx/core/djangoapps/site_configuration/models.py, openedx/core/djangoapps/site_configuration/tests/test_helpers.py
related to
#62 
#65 
#81 
#106
=> Revert multi site course changes

codecov.yml
Sets target code coverage to 70% (We will increase this as we iterate)
Turns codecov PR comments on
codecov.yml
1. (reverse merge) If you merged from the development branch into master then check to see if there are any changes in master that can be merged down to the development branch (like hotfixes, etc). In this case, use github's UI for feedback and the git command line interface for …
=> Update code coverage settings

lms/envs/common.py
This PR is edx-theme repo part of the task "removes about page". Just commented out as per discussion.
The other one is on edx-theme; https://github.com/Microsoft/edx-theme/pull/137
common.py
After depoloyment, site_url/about should not show up.
94258
1. (reverse merge) If you merged from the development branch into master then check to see if there are any changes in master that can be …
=> remove about url

codecov.yml, lms/djangoapps/courseware/tests/test_microsites.py, lms/djangoapps/static_template_view/urls.py, lms/envs/common.py
Merges 2 bug fixes from dev->release
Also merges the code coverage changes we made on devfic branch
Please follow the actual PRs for further information
Please follow the actual PRs for further information
94258 / 94611
1. (reverse merge) If you merged from the development branch into master then check to see if there are any changes in master that can be merged down to the development …
=> d2r merge for bug fixes (remove about/contact/blog/etc.. urls)

lms/envs/common.py
Reenables the FAQ MKTG_URL_LINK_MAP entry for the FAQ page and points it by default to /faq
103219
1. (reverse merge) If you merged from the development branch into master then check to see if there are any changes in master that can be merged down to the development branch (like hotfixes, etc). In this case, use github's UI for feedback and the git command line interface for the actual …
=> Fix issue with help info not showing up on login/register page sidebars

lms/djangoapps/course_api/tests/test_views.py, lms/djangoapps/course_api/views.py
This will introduce new setting "RESTRICT_COURSES_API" in courses API which needs to be added in site configurations in admin panel to restrict  the api for a specific site. 
deploy the code and add RESTRICT_COURSES_API to true in admin panel site_configurations and we can't access the site and throws error to users . url: "api/courses/v1/courses"
add this RESTRICT_COURSES_API  in admin panel and we can see the api url is restricted. and can be accessed with  access token with staff access 
1. If merging from the development branch into master (or porting changes from upstream) then use github's UI to get review feedback, but use the git command line …
=> Adding an option to restrict the access in course catalog API

lms/envs/aws.py
The list of oauth providers should include MSA (live)
n/a. short review
1. deploy openedx
1. edit both /edx/app/edxapp/*ms.env.json files
1. update "ENABLE_THIRD_PARTY_AUTH": true,
1. (if fullstack) sudo /edx/bin/supervisorctl restart edxapp:
1. (if devstack) paver commands to recompile assets and start LMS service
1. visit (LMS)/admin/third_party_auth/oauth2providerconfig/add/
1. "backend name dropdown" will now include "live" (which the original name for Microsoft Accounts or MSA)
102931
=> The list of oauth providers should include MSA (live)

lms/djangoapps/course_api/tests/test_views.py, lms/djangoapps/course_api/views.py
candidate to replace #134 
dev to release (api and test fix)
=> partial dev to release

.github/PULL_REQUEST_TEMPLATE.md
simplifying the pr template. if approved, i'll port these improvements (and any of your suggestions) to our other repos
n/a. short review
submit a pull request in edx-platform
n/a
1. If you're merging from a feature branch into the development branch then "Squash and merge" to keep our history clean.
[//]: # ( 4 …
=> cleanup2 simpler pr template

.vscode/settings.json, common/djangoapps/track/middleware.py, common/djangoapps/track/tests/test_middleware.py, common/djangoapps/track/views/__init__.py, common/djangoapps/track/views/tests/test_views.py
Anonymizes user IP address in logs if SQUELCH_PII_IN_LOGS = True in settings.FEATURES
common/djangoapps/track/middleware.py
set SQUELCH_PII_IN_LOGS in FEATURES section of lms.env.json and cms.env.json
1. (reverse merge) If you merged from the development branch into master then check to see if there are any changes in master that can be merged down to the development branch (like hotfixes, …
=> GDPR: Anonymize IP Address in tracking logs

common/djangoapps/student/views.py
What does this PR do? Please provide some context
This is PR continuation to PR-120, where i missed the some imports. 
Where should the reviewer start?
common/djangoapps/student/views.py
How can this be manually tested? (brief repro steps)
This required C# WebAPI hosted on the local machine is part of LEX TFS location. $/MLX/Prototypes/LR.ExternalLogin.Web
Admin settings as follows:
i. Create the LTI Consumer entry
ii. Configure the same secret key in C# web api's web.config
iii. Add extra Site_configurations entries
{
"external_login_api":"https://msa.rps.signing.microsoft.com/api/v1.0/ExternalLogin/Authenticate?Provider=RPS&RedirectUri=",
"SOCIAL_OAUTH_MSA_PROVIDER":"oa2-live"
}
What are the relevant TFS items? (list id numbers)
All the tasks under the story: 102365
1. If you're merging …
=> Missing imports for MSA POC

.travis.yml, codecov.yml, scripts/docker-report.sh
Adding paver coverage to the reporting script does the final step of combining 
all the test .xml files into one coverage.xml file that is uploaded to codecov
scripts/docker-report.sh
Submit a pull request
[//]: # ( 3 The book "The Checklist Manifesto: How to Get Things Right" by Atul Gawande …
=> Fixing codecov reporting

lms/djangoapps/courseware/tests/test_views.py, lms/djangoapps/courseware/views/views.py
The message displayed for cert in progress tab has been updated.
Request Certificate from progress page and we can see the message has been updated.
Before: You can keep working for a higher grade, or request your certificate now.
After: You can continue working on the course.
Request the certificate in progress tab and check for the new updated message.
87305
1. (reverse merge) If you …
=> Updated message for Certificates

common/djangoapps/student/views.py, lms/static/js/student_account/MSAMigrationStatus.js, lms/static/js/student_account/models/LoginModel.js, lms/static/js/student_account/views/LoginView.js, lms/static/js/student_account/views/RegisterView.js, openedx/core/djangoapps/user_api/views.py
=> Clean up for Email Lookup MSA login form

lms/djangoapps/student_account/views.py
=> Conditionally enable MSA migration login form

lms/static/js/student_account/views/LoginView.js
=> Improving messaging

.travis.yml
adds ci support for raccoon gang's branch
n/a. short review
submit pr into oxa/video
=> adding ci support for raccoon gang's branch

.vscode/settings.json, cms/envs/aws.py, cms/envs/common.py, cms/templates/course_outline.html, cms/templates/index.html, openedx/core/djangoapps/site_configuration/helpers.py
1) Make view-live drop down configurable
2) this will introduce new key ENABLE_MULTI_SITE_VIEWLIVE_DROPDOWN . Enabling this key will enable 
drop down in cms.
3)Changing the current implementation on multi-orgs from LMS_BASE to PREVIEW_LMS_BASE 
4) Also considering an extra scenario that returns none and returning the default value from settings.
After adding this code we can see the view live dropdown works perfectly in all scenarios, even if no value is present in admin panel.
go to CMS and check view live drop down in courses home page
1. If merging from two longterm branches (like cherry picks from upstream, dev to release, …
=> Make view-live drop down configurable

openedx/core/djangoapps/site_configuration/middleware.py
1. Changing settings from login_excempt to login_redirect urls's
2. Importing the settings from common files
=> some changes to middleware

common/djangoapps/student/views.py, lms/djangoapps/lti_provider/views.py
This PR, invoke or direct the MSA-RPS API once user is registered using Live authentication.
MSA-API redirection once new user is registered to get the PUID for logged-in user browser context (single sign-in), invoke the openedx rest api using LTI consumer approach., request will be validated using LTI signature that is generated using secret key at the consumer side. Once request been validated, API will create the social auth mapping table using uid, puid.
Where should the reviewer start?
common/djangoapps/student/views.py
How can this be manually tested? (brief repro steps)
This required C# WebAPI hosted on the local machine is part of LEX TFS location. $/MLX/Prototypes/LR.ExternalLogin.Web
Admin settings as follows:
i. Create the LTI Consumer entry
ii. Configure the same secret key in …
=> MSA RPS: User Social auth mapping

cms/templates/login.html, cms/templates/register.html, themes/red-theme/cms/templates/login.html, themes/stanford-style/lms/templates/register-form.html
Disables the autocomplete attribute on the input element where type="password"
login.html, register.html, register-form.html
Enter password within form then later come back and enter password again.  Autocomplete should not work.
Bug 104035
[//]: # ( 3 The book "The Checklist Manifesto: How …
=> Disable the autocomplete attribute on the password input field

common/djangoapps/track/middleware.py, common/djangoapps/track/views/__init__.py, common/djangoapps/track/views/tests/test_views.py, lms/envs/devstack.py
=> Anonimvideo - Anonymize video events

.github/PULL_REQUEST_TEMPLATE.md, .travis.yml, cms/templates/login.html, cms/templates/register.html, codecov.yml, common/djangoapps/track/middleware.py, common/djangoapps/track/tests/test_middleware.py, common/djangoapps/track/views/__init__.py, common/djangoapps/track/views/tests/test_views.py, lms/djangoapps/courseware/tests/test_views.py, lms/djangoapps/courseware/views/views.py, lms/envs/aws.py, scripts/docker-report.sh, themes/red-theme/cms/templates/login.html, themes/stanford-style/lms/templates/register-form.html
dev to release (anon  ip and video events, test coverage settings, cert messaging, remove autocomplete on password fields)
=> dev to release

.travis.yml
Needed for pull requests against oxa/dev.fic_new to build properly
=> Build this branch on travis

.travis.yml
Needed for pull requests against oxa/dev.fic_siteCourses to build properly
=> Build this branch on travis (oxa/dev.fic_siteCourses)

.travis.yml
Needed for pull requests against oxa/dev.fic_msa to build properly
=> Build this branch on travis (oxa/dev.fic_msa)

.travis.yml, scripts/docker-report.sh, scripts/docker-run-tests.sh
Changes code coverage compare branch to the base branch the PR is against.
If this is a Travis branch build on a long running branch, it will run coverage reports against that branch's history.
./scripts/docker-report.sh
[//]: # ( 3 The book "The Checklist Manifesto: How to Get Things Right" …
=> Fixing code coverage diff to use base branch not master

lms/djangoapps/lti_provider/views.py, openedx/core/djangoapps/user_api/accounts/api.py
Deletes user's social authentication records when deleting their account.
Cleans up the LTI api implementation to better adhere to REST standards
lms/djangoapps/lti_provider/views.py
104562
[//]: # ( 4 …
=> Delete social auth records when deleting user account

.travis.yml, lms/static/js/spec/dateutil_factory_spec.js
This will fix the random timeouts we get when pulling our large docker image in travis.
(Whenever a travis job fails after 10-12 minutes, this fixes that.)
.travis.yml
Submit a pull request
None, just needed to be fixed
[//]: # ( 3 The book "The Checklist Manifesto: How to Get Things Right" …
=> Fixing build timeouts with travis_wait

lms/lib/comment_client/thread.py, openedx/core/djangoapps/user_api/accounts/api.py
Corrected build to anonymize mongo instances of discussions when user chooses to delete his account.
1. Login
2. Enroll to a course
3. Create a discussion forum entry
3. Go to account settings and click on delete user
Login > Account Settings > Delete User
[//]: # ( 3 The book "The Checklist …
=> GDPR : Mongo Delete Implementation of Discussions

.travis.yml, package.json, scripts/docker-run-tests.sh
=> Runs apt-get update for apt install, fixes tests

cms/djangoapps/azure_video_pipeline/utils.py, cms/djangoapps/contentstore/views/tests/test_videos.py, cms/djangoapps/contentstore/views/videos.py, cms/static/js/factories/videos_index.js, cms/static/js/spec/views/active_video_upload_list_spec.js, cms/static/js/spec/views/previous_video_upload_spec.js, cms/static/js/views/active_video_upload_list.js, cms/static/js/views/previous_transcripts_video_upload.js, cms/static/js/views/previous_video_upload.js, cms/static/js/views/settings/intro_video_azure.js, cms/static/js/views/settings/main.js, cms/templates/js/settings-intro-video-azure.underscore, cms/templates/videos_index.html
@kabirkhan @sdolenc 
- upload video's status now updates smoothly - without page reloading.
=> Video Uploads: uploading video's status `hot` updating (w/o page refreshing)

common/djangoapps/student/tests/test_login.py, openedx/core/djangoapps/site_configuration/helpers.py
Fixes the title of the platform, which contains an extra pipe symbol.
Browse to the home page > Title bar.
Browse to the home page > Title bar.
Bug#90913
[//]: # ( 4 …
=> [Bug:90913] Breadcrumb and Title Fix

common/djangoapps/student/cookies.py
Sets httponly to true for student cookies (edxloggedin, edx-user-info, etc)
Login and check the cookies to verify httponly is true for user based cookies
104048
[//]: # ( 4 …
=> HTTPOnly for user cookies.

lms/static/js/student_account/views/RegisterView.js, lms/static/sass/views/_account-settings.scss, lms/static/sass/views/_login-register.scss, lms/templates/student_account/link_account.underscore
Resolve UI changes planned for sprint 49
Task [109325 Registration Confirmation Page - Need to update yellow box message](http://vstfpg03:8080/tfs/LEXENGR1/Common/_workitems/edit/109325)
Task [109329 Account Update Required Page - Update text with latest](http://vstfpg03:8080/tfs/LEXENGR1/Common/_workitems/edit/109329)
Task [109312 Sign in page - form field missing border](http://vstfpg03:8080/tfs/LEXENGR1/Common/_workitems/edit/109312)
Anywhere...
Make sure your browser remembers some account.
localhost:8000/login for task 109312
localhost:8000/register for task 109325
localhost:8000/account/link for task 109329
[109325](http://vstfpg03:8080/tfs/LEXENGR1/Common/_workitems/edit/109325)
[109329](http://vstfpg03:8080/tfs/LEXENGR1/Common/_workitems/edit/109329) …
=> Dev.fic msa styling

lms/static/js/student_account/views/RegisterView.js, lms/static/sass/views/_login-register.scss, lms/templates/student_account/register.underscore, openedx/core/djangoapps/user_api/views.py
Resolve UI changes for task [109320 Registration Confirmation Page - Update per new design](http://vstfpg03:8080/tfs/LEXENGR1/Common/_workitems/edit/109320)
Wherever you like...
go to /register and compare to design
[109320](http://vstfpg03:8080/tfs/LEXENGR1/Common/_workitems/edit/109320) …
=> Update Registration Confirmation Page per new design. Task 109320

lms/static/js/spec/student_account/account_settings_factory_spec.js, lms/static/js/student_account/views/account_settings_factory.js, lms/templates/fields/field_readonly_account.underscore
Update account settings page per [design](http://mslt-mlxbuild29/share/OXA/#g=1&p=account_settings_1) 
Anywhere...
Go to account settings page and compare design.
[109692](http://vstfpg03:8080/tfs/LEXENGR1/Common/_workitems/edit/109692)
[//]: # ( 3 The book "The Checklist Manifesto: How to …
=> Build account settings UI changes based on design. Task #109692

openedx/core/djangoapps/user_api/views.py
Change wording to lower case.
Anywhere.
By looking at the words.
[109671](http://vstfpg03:8080/tfs/LEXENGR1/Common/_workitems/edit/109671)
[//]: # ( 4 …
=> Task 109671. Lowercase Microsoft account settings.

lms/djangoapps/grades/api/v1/views.py
we are updating the user's permission to staff on the fly in request object
In bulk grades API we are giving a user staff user like access if he enter's with client credentials.
Note; this will be on the fly permission and will not be added in database and not applicable to other API's. 
user's can call the bulk grades API with Client credentials even if he was not enrolled in the course
[//]: # ( 1 Our team's policies and …
=> Updating the permissions on the fly for request object

lms/djangoapps/grades/api/v1/views.py
* Updating the permissions on the fly for request object
* Update views.py
full dev to release
=> full dev to release

lms/djangoapps/student_account/views.py, lms/static/js/student_account/views/LinkAccountView.js, lms/static/js/student_account/views/LoginView.js, lms/static/sass/views/_login-register.scss, lms/templates/student_account/link_account.underscore, lms/templates/student_account/register.underscore
'Microsoft Account' capitalization changes from test drive. Bug#109956
Account update required page paragraphs line height fix. Task#109857
Wherever
Check 'Microsoft account' in buttons/pages are correct
Check line height on page /account/link
[109857](http://vstfpg03:8080/tfs/web/wi.aspx?pcguid=9ab74427-9c65-4b98-a40f-ac564be0d72f&id=109857)
[109956](http://vstfpg03:8080/tfs/web/wi.aspx?pcguid=9ab74427-9c65-4b98-a40f-ac564be0d72f&id=109956)
[//]: # ( fyi: This content was …
=> Msa bug fixes

common/djangoapps/student/views.py, common/djangoapps/third_party_auth/middleware.py, lms/static/sass/views/_login-register.scss
squashing misc commits as a pre-requ for PR into mainline dev branch
=> squashing misc commits

.travis.yml, common/djangoapps/third_party_auth/middleware.py
=> tiny quality fix

common/djangoapps/student/views.py, common/djangoapps/third_party_auth/middleware.py, lms/djangoapps/student_account/views.py, lms/static/js/student_account/views/LinkAccountConfirmView.js, openedx/core/djangoapps/site_configuration/middleware.py, openedx/core/djangoapps/user_api/accounts/api.py
1. Disables the MSA migration check for staff and superuser users. 
2. Fixes logout redirect urls for when a user clicks 'No' to allow the MSA app permissions to their account info
site_configuration/middleware.py
[//]: # ( 3 The book "The Checklist Manifesto: How to Get Things Right" by Atul …
=> Disable msa for staff/superuser, fix user clicks 'No' for permissions logout

openedx/core/djangoapps/site_configuration/middleware.py
=> reverting code related to MSA check

common/djangoapps/student/views.py, lms/djangoapps/student_account/views.py, openedx/core/djangoapps/site_configuration/middleware.py
1. Don't migrate course staff/instructor, global staff, superusers to MSA
2. Fixes confirmation page bug.
3. Don't send user to MSA logout page if they haven't migrated their account.
site_configuration/middleware.py
=> Don't migrate staff or superuser. 

common/djangoapps/student/views.py, lms/templates/student_account/register.underscore
Signout is not working when user choose to sign-in with different account.
lms/templates/student_account/register.underscore
Get the pull request change
1. sign-in with staff account, select signout
2. sign-in msa migrated user and select singout
3. sign-in with native learner account, prompt for migration, signin and choose signin with different user account, 
4. registration with msa and choose sign-in different account on registration form
[//]: # ( fyi: This content was …
=> Logout is broken when user choose to signout during registration

openedx/core/djangoapps/user_api/accounts/api.py
Removing the condition that checks for is_active while deleting account
while delting account for GDPR, we will now delete the user accoiunt even he is not active.
[//]: # ( 4 …
=> removing the condition that checks for is_active

.travis.yml
Adding oxa/ms.fic branch to Travis
This will run test cases when a pull request is submitted to oxa/ms.fic branch
submit a pull request to oxa/ms.fic to test.
[//]: # ( 4 …
=> Adding oxa/ms.fic branch to Travis

.travis.yml
=> partial dev to release 

common/djangoapps/util/course.py
These is an issue with the Course About page URL in course settings page in CMS. It points to same LMS_ROOT_URL even if course is from different organisation
Reviewer should check for site configuration
Go to course "Schedule & Settings" page and check for about Url. It should point to correct domain as mentioned in Site Configuration
[//]: # ( 2 …
=> add site configuration on settings page in cms

lms/static/js/student_account/views/LoginView.js
It will display the correct Signin error message when User is not registered with system previously
Reviewer should look at the screenshot attached
#####New error message
[//]: # ( 4 …
=> update the error msg on signin

cms/envs/aws.py, lms/envs/aws.py
Removes "*" from the ALLOWED_HOSTS whitelist and adds 'localhost' and '127.0.0.1'.  ALLOWED_HOSTS represents the host/domain names that the Django site can serve. This is a security measure to prevent HTTP Host header attacks.  The use of "*" will match anything and defeats the purpose of having a whitelist.  For load testing purposes, "*" can be added back to the whitelist (if necessary), but production should never utilize this value.
lms/envs/aws.py and cms/envs/aws.py
Using host file entries, map domains to lms/cms then attempt to use them (result HTTP 400 - Bad request).  Modifying the host header should have a similar result. 
110829
1. If you're merging from a short-term (feature) branch into a long-term branch (like dev, release, or master) then "Squash and merge" to keep our …
=> Enforce a whitelist of allowed hosts

common/djangoapps/enrollment/data.py, common/djangoapps/enrollment/tests/test_data.py, lms/djangoapps/courseware/exceptions.py, lms/djangoapps/grades/api/urls.py, lms/djangoapps/grades/api/v1/tests/test_views.py, lms/djangoapps/grades/api/v1/urls.py, lms/djangoapps/grades/api/v1/views.py, openedx/core/djangoapps/oauth_dispatch/dot_overrides.py, openedx/core/djangoapps/oauth_dispatch/tests/test_dot_adapter.py, openedx/core/djangoapps/oauth_dispatch/tests/test_views.py
1. Client credentials
Providing unexpired token for oauth2 in client credentials
2. Bulk grades API 
Bulk grades API that returns user's grades which is  restricted to client credentials only token.   
Accessing the API with client credentials token will have the access to bulk grades API, where as other token's can't access the same. 
call bulk grades api with/with out  client credentials token.  
[//]: # ( 1 Our team's …
=>  Client credentials and grades api

cms/envs/aws.py, lms/envs/aws.py
Reverting #272. This change is breaking courses Site in BVT.
=> Revert "Enforce a whitelist of allowed hosts"

common/djangoapps/util/course.py, lms/djangoapps/bulk_email/tasks.py, lms/static/js/student_account/views/LoginView.js
=> Release to Master

.travis.yml
=> Skip JS unit tests

common/lib/xmodule/xmodule/js/spec/capa/display_spec.coffee
IT will fix MathJax js error
It escaped the special character with '//'
Ref: https://api.jquery.com/category/selectors/
[//]: # ( 4 https://github.com/Azure/azure-event-hubs/blob/master/.github/PULL_REQUE …
=> escaped special character with double backslash

.travis.yml, cms/djangoapps/contentstore/views/error.py, cms/envs/common.py, cms/urls.py, common/djangoapps/util/views.py, common/lib/xmodule/xmodule/js/spec/capa/display_spec.coffee, lms/djangoapps/static_template_view/urls.py, lms/djangoapps/static_template_view/views.py, lms/envs/common.py, lms/urls.py
=> Dev to Release branch

.travis.yml, cms/djangoapps/contentstore/views/error.py, cms/envs/common.py, cms/urls.py, common/djangoapps/util/views.py, common/lib/xmodule/xmodule/js/spec/capa/display_spec.coffee, lms/djangoapps/static_template_view/urls.py, lms/djangoapps/static_template_view/views.py, lms/envs/common.py, lms/urls.py
Merge from Release to Production
=> Merge from Release to Production

cms/envs/aws.py, lms/envs/aws.py
Most web servers are configured to pass unrecognized/arbitrary host headers to the first virtual host.  This change mitigates a host header attack by providing a whitelist for both LMS/CMS during installation. 
Any of the files.
1) Deploy STAMP specifying a whitelist of hostnames for LMS/CMS.
e.g.  -EdxAppLmsAllowedHosts "lms-openedx-tm.trafficmanager.net,preview-openedx-tm.trafficmanager.net" -EdxAppCmsAllowedHosts "cms-openedx-tm.trafficmanager.net"
2) Verify that lms.env.json and cms.env.json contain their respective whitelists (LMS_ALLOWED_HOSTS and CMS_ALLOWED_HOSTS)
3) Verify that LMS/CMS continue to function as expected.
Bug 110829
1. If you're merging from a short-term (feature) branch into a long-term branch (like dev, release, or master) then "Squash and merge" to keep our …
=> Provide a whitelist of allowed hostnames to mitigate a host header attack

.github/PULL_REQUEST_TEMPLATE.md
Simplifying the pr template. if approved, i'll port these improvements (and any of your suggestions) to our other repos
n/a. short review
submit a pull request in edx-platform
n/a
1. If you're merging from a feature branch into the development branch then "Squash and merge" to keep our history clean.
[//]: # ( 4 …
=> Pull Request Template 

common/djangoapps/track/management/commands/ship_tracking_logs.py, lms/djangoapps/instructor_task/models.py, lms/envs/aws.py, openedx/core/storage.py, requirements/edx/base.txt
Add azure storage + transaction log shipping changes
Code Change
=> Add azure storage + transaction log shipping changes

lms/static/js/student_account/views/RegisterView.js
=> Error msg fixes while Registration

lms/static/js/student_account/views/RegisterView.js
It will update the error message, when full name is returned empty from MSA on the registration page
=> err message fix

lms/static/js/student_account/views/RegisterView.js
fix full name error issue 
err message fix 
=> Dev to Release Sprint 62

cms/envs/aws.py, lms/envs/aws.py
Removes the hard-coded lists from edx-platform/lms/envs/aws.py and edx-platform/cms/envs/aws.py and moves them into Ansible configuration.
lms/envs/aws.py
cms/envs/aws.py
1) Deploy Hawthorn
2) Verify that lms.env.json and cms.env.json contain their respective whitelists as per the LMS/CMS configured values
3) Verify that LMS/CMS continue to function as expected.
Bug 110829
Task 65310
[//]: # ( 1 Our team's policies and …
=> Hawthorn: Move the whitelist of allowed hostnames to mitigate a host header attack to Ansible configuration 

cms/envs/aws.py, common/djangoapps/student/cookies.py, lms/envs/aws.py
=> Security related changes

cms/envs/aws.py, common/djangoapps/student/cookies.py, lms/envs/aws.py
=> Security Changes

cms/envs/aws.py, common/djangoapps/track/management/commands/ship_tracking_logs.py, lms/djangoapps/instructor_task/models.py, lms/envs/aws.py, openedx/core/storage.py, requirements/edx/base.in, requirements/edx/base.txt
=> Enabling Azure Storage Support

common/djangoapps/student/views.py
this will diable msa migration flow.
After merging this code, msa migration flow will be disabled. 
=> Addding changes to disable msa migration

cms/templates/login.html
It will automatically redirect to Azure AD login page
=> auto login in CMS for Azure AD

lms/djangoapps/student_account/views.py, lms/static/js/student_account/views/account_settings_factory.js, lms/templates/student_account/account_settings.html
Based on the configuration "ENABLE_MSA", 
this makes the fiels read only and hide other fields 
deploy and enable ENABLE_MSA and re-compile the assets. 
[//]: # ( 4 …
=> Make account settings page read only/hide based on configuration

cms/djangoapps/contentstore/views/library.py, cms/djangoapps/course_creators/views.py
Adding course authors to access the library creation
this will provide the ability to create library for course authors
[//]: # ( 4 https://github.com/Azure/azure-event-hubs/blob/master/.github/PULL_REQUE …
=> Adding course authors to access the library creation

cms/djangoapps/contentstore/views/library.py, cms/djangoapps/course_creators/views.py
=> Release to Prod (Hot fix)

openedx/core/storage.py
Updates init signature, removes listdir since it is now available in the superclass, adds url method override to ensure that sas token is created.
storage.py
Test via deployment
Task 247629
[//]: # ( 4 …
=> Storage.py updates for Hawthorn

common/lib/xmodule/xmodule/contentstore/mongo.py
The change is unnecessary since we are not attempting the CosmosDB option.
=> Revert "[INTERIM] Reverting edX Hack since using Mongo-3.4 (CosmosDB)"

lms/envs/aws.py, lms/envs/common.py
Making the display of course discovery and dashboard tabs configurable
The review must happen in 3 places:
1. Start with the end result in theming [PR#198](https://github.com/Microsoft/edx-theme/pull/198)
2. Base configuration in edx-configuration [PR#397](https://github.com/Microsoft/edx-configuration/pull/397)
3. and finally in edx-platform feature reference [PR#465](https://github.com/Microsoft/edx-platform/pull/465) …
=> Making the display of course discovery and dashboard tabs configurable

common/djangoapps/course_modes/models.py, lms/envs/aws.py, lms/envs/common.py
Making Honor mode eligible for certificate
=> Making Honor mode eligible for certificate

lms/djangoapps/student_account/test/test_views.py, lms/djangoapps/student_account/urls.py, lms/djangoapps/student_account/views.py, lms/envs/aws.py, lms/templates/widgets/cookie-consent.html, lms/urls.py
Adds platform support for cookie banner required for GDPR compliance
Any files
Deploy Hawthorn and enable the comprehensive theme
Task 388783
[//]: # ( 4 …
=> Add cookie banner to comprehensive theme for Hawthorn

cms/envs/aws.py, lms/envs/aws.py, lms/envs/azure_msi_key_vault.py
Prerequisites: 
This change   has the dependency with [Azure MSI ](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/tutorial-linux-vm-access-arm)
This will read/override the configurations and secrets from azure key vault. 
Right now configs and secrets are read from lms.env.json&lms.auth.json and cms.env.json&cms.auth.json files. 
This change will take the secrets from azure keyvault and override the keys extracted from *.json files.  
we have to provide the following configs in json files (need to add in [configuration repo](https://github.com/edx/configuration/blob/master/playbooks/roles/edxapp/defaults/main.yml) ) to read from keyvault:
```
In lms.env.json: 
"AZURE_MSI_REQUEST_URI" : "http://169.254.169.254/metadata/identity/oauth2/token", …
```
=> Reading/Overriding configurations and Secrets from azure keyvault with MSI

cms/urls.py, lms/djangoapps/student_account/views.py, lms/envs/aws.py, lms/envs/common.py, lms/urls.py
Add option for enabling/disabling custom authentication. There are 3 parts to this change:
1. Theming changes to support single button login [PR#201](https://github.com/Microsoft/edx-theme/pull/201)
2. Feature plumbing - [PR#400](https://github.com/Microsoft/edx-configuration/pull/400)
3. Feature creation - [PR#471](https://github.com/Microsoft/edx-platform/pull/471)
Any of the three options above
[//]: # ( 1 Our team's …
=> Add option for enabling/disabling custom authentication

openedx/core/djangoapps/user_api/accounts/views.py
=> Bug fix for user_email

openedx/core/djangoapps/user_api/accounts/tests/test_retirement_views.py, openedx/core/djangoapps/user_api/accounts/views.py, openedx/core/djangoapps/user_api/urls.py
Cherry-pick Bulk retirement changes from master branch to RC
=> Change bulk delete retirements to a POST

lms/urls.py
we have a [duplicate ](https://github.com/Microsoft/edx-platform/blob/86a0dbd0a330fccb91835b6ba81fae868401d0be/lms/urls.py#L614)reference to the URL for student_account django app. 
Removing duplicate reference to account settings urls
[//]: # ( 3 The book "The Checklist Manifesto: How to Get …
=> Remove duplicate reference to account settings urls

cms/envs/aws.py, lms/envs/aws.py
Renaming API_VERSION config to KEYVAULT_API_VERSION
=> Renaming API_VERSION config to KEYVAULT_API_VERSION

openedx/core/djangoapps/lang_pref/middleware.py, openedx/core/djangoapps/lang_pref/views.py
Sets the secure attribute on the language cookie
Either file
1) Deploy Hawthorn
2) Navigate to https://courses.bvt.oxa.microsoft.com/password_reset/
3) Check the Set-Cookie: openedx-language-preference parameter for the secure attribute
Task 877056
[//]: # ( 3 The book "The Checklist …
=> Set the secure attribute on the language cookie

lms/djangoapps/lti_provider/urls.py
correcting the import error for lti 
Thsi should be part of https://github.com/Microsoft/edx-platform/pull/483
[//]: # ( 4 https://github.com/Azure/azure-event-hubs/blob/master/.github/PULL_REQUEST_TEMPLA …
=> Fixing the import error for lti provider

common/djangoapps/student/models.py, openedx/core/djangoapps/user_api/accounts/views.py
This allows the Random SALTS unique for every request, and also allows the third party agent to mark user for retirement using the puid
[//]: # ( 4 …
=>  Random SALT keys unique per request,  third party agent marks user for retirement using puid

cms/envs/aws.py, lms/envs/aws.py
Renaming keyvault api version variable name
=> Renaming keyvault api version variable name

common/djangoapps/student/cookies.py
Adds the secure attribute to edxloggedin cookie when HTTPS is used.
cookies.py
1) Deploy Hawthorn
2) Navigate to a page
3) View the edxloggedin cookie to ensure that the secure attribute is present
Task 877056
[//]: # ( 3 The book "The Checklist Manifesto: How to Get Things Right" by Atul …
=> Add the secure attribute to edxloggedin cookie

openedx/core/djangoapps/user_api/accounts/views.py
making the retire api work _ temp fix
=> making the retire api work

lms/djangoapps/course_api/views.py
Adding option to restrict the access in course catalog for CourseDetailView api 
=> Adding option to restrict the access in course catalog

lms/djangoapps/course_api/tests/test_views.py
Removing shard which is breaking the deployment 
=> Removing shard which is breaking the deployment

common/djangoapps/student/cookies.py, openedx/core/djangoapps/lang_pref/views.py
Forces cookie secure attribute equal to true for EDXMKTG_LOGGED_IN_COOKIE_NAME, EDXMKTG_USER_INFO_COOKIE_NAME and LANGUAGE_COOKIE
Any file
1) Deploy Hawthorn
2) Check the response header for https://courses.bvt.oxa.microsoft.com/create_account/
to ensure that the respective cookies have the secure attribute 
Task 877056
[//]: # ( 2 …
=> Force the secure attribute equal to true for various cookies

common/djangoapps/student/cookies.py
Fixes a casing issue which causes a 500 error
cookies.py
Deploy Hawthorn.  Ensure that lms/preview sites load after login and that the respective cookies have the secure attribute.
[//]: # ( 4 …
=> Fix casing issue

openedx/core/djangoapps/user_api/accounts/views.py
Deletes the puid entry for the user from the third_party_social_auth_mapping table
=> Bug fix delete the entry from Third party social Auth mapping table

cms/envs/common.py, cms/urls.py, lms/envs/common.py, lms/urls.py
Merge changes related to AMS Embedded video player to hawthorn
=> Merge: Enable Azure Media Service Xblock for Embed Video Player

cms/envs/common.py, cms/urls.py, lms/envs/common.py, lms/urls.py
Merge changes related to AMS Embedded video player to hawthorn and updated the urlpatterns for Azure Media Xblock
[//]: # ( 4 https://github.com/Azure/azure-event-hubs/blob/master/.github/PULL_REQUEST_TEM …
=> Enable Azure Media Service Xblock for Embed Video 

cms/envs/common.py, cms/urls.py, lms/envs/common.py, lms/urls.py
* Merge: Enable Azure Media Service Xblock for Embed Video Player (#502)
* update azure media player xblock urlpatterns
* removed unnecessary import
[//]: # ( 4 …
=> Release to production - Embed fix

openedx/core/djangoapps/user_api/accounts/views.py
Add error handler for DoesNotExist on the UserSocialAuthMapping model and force a return of 404 instead of 500 when deactivate_logoutv2 api is called.
The changes below.
N/A
N/A
[//]: # ( 4 …
=> Handle DoesNotExist error for UserSocialAuthMapping model

openedx/core/djangoapps/user_api/accounts/views.py
Add support for dynamically (fully site-configuration based) extending the response from the retirement queue response. 
The changes below
N/A
N/A
[//]: # ( 4 …
=> Add support for extending the retirement queue response

common/djangoapps/util/course.py
=> course about url based on the org

common/djangoapps/util/course.py
=> Dev to Production: about url based on the org

openedx/core/djangoapps/user_api/accounts/views.py
=> Social auth account deletion moved to last step

openedx/core/djangoapps/user_api/accounts/views.py
* Social auth account deletion moved to last step
* add missing delete
* fixes to user social mapping
=> Dev to Production: Social auth account deletion moved to last step (#515)

requirements/edx-sandbox/base.in, requirements/edx-sandbox/base.txt
Hawthorn build failed due to matplotlib. It is fixed in ironwood version
https://discuss.openedx.org/t/hawthorn-master-native-build-breaks-runtimeerror-python-version-3-5-required/153/5
Applying the similar fix in hawthorn:
https://github.com/edx/edx-platform/commit/644bb41b87f52cd39ff33ea7375fb21d1a294aeb
[//]: # ( 2 https://github.com/sprintly/sprint.ly-culture/blob/master/pr- …
=> matplotlib fix

requirements/edx-sandbox/base.in, requirements/edx-sandbox/base.txt
Fix broken dependency related to matplotlib
Hawthorn build failed due to matplotlib. It is fixed in ironwood version
https://discuss.openedx.org/t/hawthorn-master-native-build-breaks-runtimeerror-python-version-3-5-required/153/5
Applying the similar fix in hawthorn:
edx@644bb41
[//]: # ( 3 …
=> matplotlib fix (#517)
