microsoft/edx-platform

common/lib/xmodule/xmodule/js/spec/problem/edit_spec_hint.coffee
Fixed the bad word 'ass' which was found with policheck tool
No need to make any other change. Other Policheck errors are false-alarm:
- lez words are in French locale. So they look ok. There is no lez word in English contexts.
- I couldn't find the topless word in the edx-platform code base 
- I cannot see any wtf word in the platform. It is seen in some binary files and file names but that is ok.
- I cannot see any f* word in the platform
- cum words are not in English. They are in a different language and I looked from translator and they look ok sentences. 
@Microsoft/lex
=> Fixed the bad word 'ass' which was found with policheck tool

cms/templates/404.html, cms/templates/500.html, cms/templates/error.html, cms/templates/register.html
1) I added the URL for Terms of Service on CMS register page.
2) On the CMS 404 and 500 error pages I removed the e-mail address and added "contact support text"
@Microsoft/lex
=> CMS TOS link and error pages changes

cms/templates/register.html, common/djangoapps/student/views.py, lms/envs/common.py
1) If account is not activated do not let the user to enroll in a course and show the error message
"This account has not been activated yet. Please first activate your account by clicking the link in the sent activation e-mail."
2) In the lms/envs/common.py there was this line:
COPYRIGHT_YEAR = "2015"
This value is used in CMS pages like registration and footer. It was always showing 2015 for Copyright Year.
I fixed it with 
COPYRIGHT_YEAR = datetime.date.today().year 
so that it uses the current year. 
3) I put target="_blank" in the registration pages of CMS so that so that TOU opens in a new window/tab instead of taking over the current page. (I submitted another PR for fixing this in LMS with theming)
@Microsoft/lex
=> Don't let enrolling course before activation, COPYRIGHT_YEAR fix and target="_blank" fix for links

common/djangoapps/student/models.py
Commented out education levels high school and below so that they are not displayed on account settings page.
We hid this on registration page. But account_settings page is not part of theming and we have to hide them here separately. 
@Microsoft/lex
=> Commented out education levels highschool and below for account settings page

common/djangoapps/student/views.py
Add code to check site_configuration value for ENFORCE_PASSWORD_POLICY instead of just settings.FEATURES. This solves the error users registering with Azure Active Directory not being able to register because of Password Policy. Caveat: In non-base site, provide the configuration value "ENFORCE_PASSWORD_POLICY": false in the values field of the site configuration.
**Reason**
Azure AD Login was throwing a bad password error when creating the account. This change allows configuration values to be set in Site Configurations to turn off or on "ENFORCE_PASSWORD_POLICY" by site.
=> Add code to check site_configuration value for ENFORCE_PASSWORD_POLICY

common/lib/xmodule/xmodule/video_module/video_handlers.py
This PR includes a fix for this error 'TypeError: You cannot set the body to a text value without a charset' which was cherry-picked from https://github.com/edx/edx-platform/pull/14548.
=> Fixes error 'TypeError: You cannot set the body to a text value without a charset'

cms/urls.py, common/djangoapps/student/tests/test_views.py, common/djangoapps/student/views.py
- when user clicks on signout it will redirect to signin page.
- signin into lms or cms and click signout .
- Before : signout redirect to main home page.
After : signout redirect to signin page.
Bug : 84811
- [x ] Title of the pull request is clear and informative
1. (reverse merge) If you merged into master then check to see if there are any changes in …
=> Automatic sign-out should redirect to the sign-in page

common/djangoapps/student/tests/test_create_account.py, common/djangoapps/student/tests/test_password_policy.py, common/djangoapps/student/views.py, common/djangoapps/third_party_auth/tests/specs/base.py, openedx/core/djangoapps/external_auth/tests/test_ssl.py
holding back multi-org courses in edx-platform (originally PR 40)
=> Revert "Set 'created_on_site' UserAttribute on account creation"

openedx/core/djangoapps/user_api/accounts/api.py
Removing the code that stores user's previous email as part of msa migration
user's META will no longer store old_email of user
Migrate a user with MSA migration flow and check if old email is stored in user's meta data. 
152303
[//]: # ( 3 The book "The Checklist Manifesto: How to Get Things …
=> Removing old_email from user meta data

lms/djangoapps/bulk_email/tasks.py
This will fetch the site configuration based on the Organization to which course belongs and add it to the course URL Prreviously it was fetching common LMS_ROOT_URL as a result even courses from different organization were getting same LMS_ROOT_URL. 
Reviewer should check for the site configuration code
As an instructor user should go to insturctor tab and send a course invite email and check that in the course email template course link is pointing to correct LMS URL
Bug_103970
=> fixed course url in course email template

cms/djangoapps/contentstore/views/public.py, cms/envs/aws.py, cms/envs/common.py, cms/static/js/factories/register.js, cms/static/sass/partials/cms/theme/_variables-v1.scss, cms/static/sass/views/_account.scss, cms/templates/login.html, cms/templates/register.html, cms/urls.py, common/djangoapps/third_party_auth/tests/test_decorators.py
**Description:** shares third-party auth backends usage to the CMS (similar to the LMS flow).
**Background**: currently, there is a very convenient feature to perform authentication via social services (like LinkedIn, Azure services, etc.). But it is present in LMS exclusively. For some reason it is not available in Studio. Till now.
This patch is intended to share this convenience to CMS app too.
**LMS Updates**: none.
**CMS Updates**: 
- `cms/envs/common.py` - 'third_party_auth' app is registred;
- `cms/urls.py` - urls are extended under feature-flag;
- `cms/envs/aws.py` - AUTHENTICATION_BACKENDS extended under feature-flag with 3rd-party-auth backends:
-  google,
- linkedin,
- facebook,
- azuread;
- frontend (styles, template, js): auth form is adapted (see screenshots):
- to show …
=> Add third-party-auth to CMS

cms/djangoapps/contentstore/views/error.py, common/djangoapps/util/views.py, lms/djangoapps/static_template_view/urls.py, lms/djangoapps/static_template_view/views.py
This PR will let comprehensive theme to work for error pages. Even if we add 404 and 500 error pages html in comprehensive theme, openedx is unable to load and render the default 404/500 page instead. This is a known bug and fixed in new release of edx
Didn't wanted to do a cherry-pick as there are lot of other changes which might affect our oxa/dev.fic branch
Review should look at the already created ticket in Openedx
https://openedx.atlassian.net/browse/CRI-75
and PR related to solution in edx/platform
https://github.com/edx/edx-platform/commit/67442c26412c78471944a957d91e3bf8ac69390f
It can be tested by providing any invalid URL
1. If you're merging from a short-term (feature) branch into a long-term branch (like dev, release, or master) then "Squash and merge" to keep our history …
=> added comprehensive themes to error pages in LMS and Studio

lms/envs/common.py, openedx/core/djangoapps/site_configuration/middleware.py, openedx/core/djangoapps/site_configuration/tests/test_middleware.py
What's this PR do? Any additional context?
Allows for individual sites to be restricted to only logged in users.
Allows certain urls to be enabled for all users using regex expressions
Formatting change to a previous change also seeped into this PR in common/djangoapps/student/forms.py
Where should the reviewer start?
openedx/core/djangoapps/site_configuration/middleware.py:LoginRequiredMiddleware
How can this be manually tested? (brief repro steps)
Enable sites
Pick a site and edit its site configuration values
{
"RESTRICT_SITE_TO_LOGGED_IN_USERS": true,
"LOGIN_EXEMPT_URLS": [
"^about"
]
}
Without logging in, attempt to access the root url: '/'
You should be redirected to login
Without logging in, attempt to access the about url: '/about'
You should be able to view this page.
What are …
=> middleware that can be configured through Site Configuration to restrict a particular sites pages to logged in users

common/djangoapps/student/cookies.py
Sets httponly to true for student cookies (edxloggedin, edx-user-info, etc).  This ensures that a browser does not allow a client-side script to access the session cookie.
common/djangoapps/student/cookies.py 
Login and check the cookies to verify httponly is true for user based cookies
Bug 104048
Task 65320
[//]: # ( 2 …
=> Hawthorn: Set HttpOnly to true for student cookies 

common/lib/xmodule/xmodule/contentstore/mongo.py
This change reverts a hack edX used to support case-insensitive sorting on Mongo 3.2. The aggregation pipeline technique doesn't work as expected on CosmosDB. Given the implicit intention revert the hack when edX migrates to Mongo 3.4 and the fact that CosmosDB is Mongo 3.4, this change reverts the hack. This change is marked INTERIM because I'd like to ensure that the existing functionality remains in place while still supporting clients with Mongo 3.4+ (most likely a branching statement)
See additional context in https://openedx.atlassian.net/browse/EDUCATOR-2221
1. If merging from two longterm branches (like cherry picks from …
=> [INTERIM] Reverting edX Hack since using Mongo-3.4 (CosmosDB)

cms/envs/common.py, lms/envs/common.py
Social Django defaults to HTTP scheme when generating redirect_uri during OAuth authentication. It is, therefore, necessary to add this setting to support changing the redirect_uri to HTTPS. 
Defaulting to False (default behavior) and expecting the client to override.
The change.
N/A
[//]: # …
=> Adding support for REDIRECT_IS_HTTPS to support HTTPS redirect_uri in Social Django

lms/djangoapps/student_account/urls.py
`This will disable password reset endpoint based on configuration from admin panel(site _configuration)
`
`Defaulted to true, To make it compatible with existing behavior` 
[//]: # ( 4 …
=> [Hawthorn] Disable password reset endpoint based on configuration value

cms/envs/aws.py, lms/envs/aws.py
Social Django defaults to HTTP scheme when generating redirect_uri during OAuth authentication. It is, therefore, necessary to add this setting to support changing the redirect_uri to HTTPS.
Defaulting to False (default behavior) and expecting the client to override. This change completes the plumbing of the new setting from [PR#461](https://github.com/Microsoft/edx-platform/pull/461)
[//]: # ( 1 Our team's policies and …
=> Fix plumbing for REDIRECT_IS_HTTPS configuration

common/djangoapps/student/models.py
The SALT Keys for edx GDPR implementation is hardcoded which prevents the user from using the retired email to register back again.
This PR will randomize the SALT keys to anonymize the username and email. therefore making the username and email irreversible and also enables the user to re-register with the retired email
\lms\envs\common.py to understand the current implementation of the SALT keys
\common\djangoapps\student\models.py for the SALT key randomization
N/A
=> Randomizing SALT Keys

lms/djangoapps/course_api/tests/test_views.py, lms/djangoapps/course_api/views.py
Adding an option to restrict the access in course catalog API. cherrypicked from (#129)
deploy the code and add RESTRICT_COURSES_API to true in admin panel site_configurations and we can't access the site and throws error to users . url: "api/courses/v1/courses"
Add this RESTRICT_COURSES_API in admin panel and we can see the api url is restricted. and can be accessed with access token with staff access
[//]: # ( 1 Our team's …
=> Adding an option to restrict the access in course catalog API 
